// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_ISOsvQs43lcuorKMlNiBeV6Ew1NoJI',
    appId: '1:201176252968:web:ea6c8dc56016a9a079ab1d',
    messagingSenderId: '201176252968',
    projectId: 'yemek-8efbf',
    authDomain: 'yemek-8efbf.firebaseapp.com',
    storageBucket: 'yemek-8efbf.firebasestorage.app',
    measurementId: 'G-2H06MLJF5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByGNxJkHoVPaNl4DmwKLeg9I1yLJxsblA',
    appId: '1:201176252968:android:925b0c4899dd1a2479ab1d',
    messagingSenderId: '201176252968',
    projectId: 'yemek-8efbf',
    storageBucket: 'yemek-8efbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDwwgnGY_SIg0o64UaDpNr6g4kzHZ68Lc',
    appId: '1:201176252968:ios:1ef6c4331e45a2d779ab1d',
    messagingSenderId: '201176252968',
    projectId: 'yemek-8efbf',
    storageBucket: 'yemek-8efbf.firebasestorage.app',
    iosBundleId: 'com.example.yemekTarifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDwwgnGY_SIg0o64UaDpNr6g4kzHZ68Lc',
    appId: '1:201176252968:ios:1ef6c4331e45a2d779ab1d',
    messagingSenderId: '201176252968',
    projectId: 'yemek-8efbf',
    storageBucket: 'yemek-8efbf.firebasestorage.app',
    iosBundleId: 'com.example.yemekTarifi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw_ISOsvQs43lcuorKMlNiBeV6Ew1NoJI',
    appId: '1:201176252968:web:c2d2d957255f03b279ab1d',
    messagingSenderId: '201176252968',
    projectId: 'yemek-8efbf',
    authDomain: 'yemek-8efbf.firebaseapp.com',
    storageBucket: 'yemek-8efbf.firebasestorage.app',
    measurementId: 'G-Z6Z44FFJXQ',
  );
}
